### ISSUE TITLE
Controller : required property runtimes.manifest still not set

### ISSUE THREAD

**Issue by ddragosd** [openwhisk/openwhisk-devtools#11]
We should update the way `whisk.properties` is generated so that when required properties get updated we generate them automatically vs maintaining them manually. One idea would be to use the existing ansible script `properties.yml`.

**Comment by rabbah** [comment]
👍

**Comment by ddragosd** [comment]
I've tried using ansible to generate `whisk.properties` and I found myself having to maintain a separate ansible environment file. Since this file is outside the main `openwhisk` repo it would be maintained separately, still requiring manual editing to keep it up to date with the changes in the upstream repo. This is similar to maintaining the environment variables for docker compose which is already in place so the PR builds on top of that.

**Comment by markusthoemmes** [comment]
@ddragosd an idea I expressed on the devlist was to completely move away from `whisk.properties` (and consul env storing) for our components.

The way I currently prefer (and don't have the bandwidth to work on) is to use typesafe Config for each component (controller/invoker) and completely switch away from `WhiskConfig`. That way, each component would have convenient defaults for the respective values. Would that make sense?

**Comment by ddragosd** [comment]
👍 . I'll keep env vars. thanks @markusthoemmes and @rabbah
