### ISSUE TITLE
Missing Controller Configuration in Consul

### ISSUE THREAD

**Issue by fmeschbe** [openwhisk/openwhisk-devtools#4]
Running docker compose has Consul waiting for the Controller with repeated messages like this:

> 2017/01/24 15:01:15 [WARN] agent: http request failed 'http://172.18.0.9:8888/ping': Get http://172.18.0.9:8888/ping: dial tcp 172.18.0.9:8888: getsockopt: connection refused

The Controller fails to startup as it is not supplied with the `whisk.system.key` property logging the following at the end:

> [2017-01-24T18:08:18.043Z] [INFO] [??] [WhiskConfig] reading properties from consul at consul.docker:8500
> [2017-01-24T18:08:20.989Z] [WARN] [??] [WhiskConfig] failed to read properties from consul: null
> [2017-01-24T18:08:21.011Z] [ERROR] [??] [Config] required property whisk.system.key still not set

Apparently Consul is expected to be supplied with Controller configuration which the Controller will then retrieve from Consul. As seen in the log, Consul does not have such configuration.

In the Ansible setup the `properties.yml` playboook which in turn is "called" from the `postdeploy.yml` playbook prepares a properties file which is loaded into Consul. These properties are used to actually configure the Controller.

Looks like these configuration properties are not generated in the docker compose build.

_Note:_ Manually configuring the `whisk.system.key` property from the `ansible/files/auth.whisk.system` file enables the controller to start and Consul be able to connect to the Controller.

**Comment by markusthoemmes** [comment]
Looking at this again, `docker-compose` already seems to have adopted the approach I proposed on the mailing list and only uses the environment of the components to pass in configuration.

**Comment by ddragosd** [comment]
referencing the thread mentioned by @markusthoemmes - https://lists.apache.org/thread.html/7f3a3f720e412f5ddb0651f56bba222ffef3c797beb615a34456d66c@%3Cdev.openwhisk.apache.org%3E

**Comment by ddragosd** [comment]
@fmeschbe thanks for investigating the issue and making it easy to apply a fix. I was able to take a look at this today and I'm preparing the PR.

**Comment by cagataygurturk** [comment]
I am unfortunately getting the same (or rather similar) error.

```
ubuntu@openwhisk:~$ tail -f ~/tmp/openwhisk/controller/logs/controller_logs.log
[2017-05-09T10:39:01.725Z] [INFO] [??] [Config] environment set value for kafka.host
[2017-05-09T10:39:01.725Z] [INFO] [??] [Config] environment set value for db.password
[2017-05-09T10:39:01.725Z] [INFO] [??] [Config] environment set value for db.provider
[2017-05-09T10:39:01.725Z] [INFO] [??] [Config] environment set value for limits.triggers.fires.perMinute
[2017-05-09T10:39:01.726Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.concurrent
[2017-05-09T10:39:01.726Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.perMinute
[2017-05-09T10:39:01.726Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.concurrentInSystem
[2017-05-09T10:39:01.726Z] [INFO] [??] [WhiskConfig] reading properties from consul at consul.docker:8500
[2017-05-09T10:39:07.556Z] [WARN] [??] [WhiskConfig] failed to read properties from consul: null
[2017-05-09T10:39:07.566Z] [ERROR] [??] [Controller] Bad configuration, cannot start.
```

and

```docker logs openwhisk_consul_1``` gives me:

```
    2017/05/09 10:40:00 [WARN] agent: http request failed 'http://172.18.0.8:8085/ping': Get http://172.18.0.8:8085/ping: dial tcp 172.18.0.8:8085: getsockopt: connection refused
    2017/05/09 10:40:06 [WARN] agent: http request failed 'http://172.18.0.8:8085/ping': Get http://172.18.0.8:8085/ping: dial tcp 172.18.0.8:8085: getsockopt: connection refused
    2017/05/09 10:40:07 [WARN] agent: http request failed 'http://172.18.0.8:8085/ping': Get http://172.18.0.8:8085/ping: dial tcp 172.18.0.8:8085: getsockopt: connection refused
```

**Comment by ddragosd** [comment]
@cagataygurturk For now feel free to use https://github.com/apache/incubator-openwhisk-devtools/pull/25. It uses rev `6a56c45` of OpenWhisk. 

@markusthoemmes @rabbah I also noticed that with the latest versions of OW from the `master` branch, the controller doesn't say explicitly which environment variable was not set, and instead it only prints
```[Controller] Bad configuration, cannot start.```
Do you have any suggestions here ?

**Comment by rabbah** [comment]
Hmm. The log above shows consul property wasn't defined. Are you saying that property is ambiguous?


-r

**Comment by duynguyen** [comment]
@rabbah I have opened #29 as this doesn't appear to relate to consul property afaics. Let's move the discussion in there.
